### PR TITLE
Add links for individual codes

### LINKED ISSUE #5: Unique URLs for individual codes
It would be good to be able to link to an individual code, rather than just a codelist.

This could mean generating a page per code, or it could be done in javascript, or using page anchors.

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #5.

NB the inline style here is to compensate for the sticky nav. I don’t know if this is better off in a stylesheet? But it looks like we don’t have one yet, and I wasn’t sure how to add one!

### CODE REVIEW

**Comment by andylolz** [comment]
Hmm… There’s a more general bug here related to internal anchors. I wonder if we use `router-link`s, we might get the nice javascripty scrolling that happens on the vuepress docs (see e.g. https://v1.vuepress.vuejs.org/guide/markdown.html#links )

**Comment by andylolz** [comment]
UPDATE: I tinkered with this for a bit (tried putting `router-link`s in) and I didn’t manage to get it working.

**Comment by andylolz** [comment]
Thanks for fixing this, @markbrough! Your changes look good && work for me.

I made one change (removing the offset, just for consistency). I hope that is okay!

**Comment by markbrough** [comment]
Sure, looks good to me!

**Pull request merged**
